### ISSUE TITLE
Haven't received the customized order status email.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/custom-order-statuses-woocommerce#109]
**Describe the bug**
Haven't received the customized order status email.

**To Reproduce**
1. Install the latest live copy which is v2.3.0
2. Create a custom order status. https://app.screencast.com/5acOdux0huHtd
3. Assign that status to any payment gateway. https://app.screencast.com/D7iw8F2W0sub1
4. Enabled email section and set custom order status. https://app.screencast.com/NM6PxUMm6WovC
5. Placed an order. https://app.screencast.com/nR8YUeH69uNYL
6. Email notification for order placed is received by admin and customer but I haven't received customized order status email. 

**Expected behavior**
Haven't received the customized order status email.

**Comment by mokshasharmila13** [comment]
"I am currently working to resolve this issue."

**Comment by mokshasharmila13** [comment]
This issue is not replication to me. I have taken a live copy from Github and tested all the steps as given, but the expected behaviour is working well.
