### ISSUE TITLE
Stock does not get updated when custom order status is changed.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/custom-order-statuses-woocommerce#20]
The client is having an issue that stock is not getting updated when custom order status is changed also by keeping the "Make custom status orders paid" option as enabled.
Suppose, when the status is changed from on-hold to dispatch, the stock is not getting reduced like it does with default status processing and completed.

Ticket Link: https://tychesoftwares.freshdesk.com/a/tickets/15483

**Comment by kenil802** [comment]
Another client has also faced the same issue.

Ticket link https://tychesoftwares.freshdesk.com/a/tickets/18346

**Comment by PratapDungrani** [comment]
@apeksha10 @kartikparmar inventory count decreases for me. Could you please check if it works on your side as well?

Thanks

**Comment by PratapDungrani** [comment]
It is working properly. No action required.

**Comment by apeksha10** [comment]
Yes, Not able to replicate
