### ISSUE TITLE
Orders are getting deleted which has the custom order status when the plugin is deleted.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/custom-order-statuses-woocommerce#21]
The client is having an issue where the orders are getting deleted which as the custom order statuses when the plugin is deleted.

Instead the orders should not get deleted.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/16489

**Comment by Shasvat7** [comment]
After taking the latest git copy, i am still able to replicate this issue.
Hence, i am opening this issue again.

**Comment by nitin-ts** [comment]
Hello,

I have created two custom statuses and placed orders with those statuses
https://i.imgur.com/GW9a20T.png

then I have set fallback status "Pending Payment" and delete the plugin and it sets Pending payment to both the orders having custom statuses
https://i.imgur.com/u4WjiAQ.png
https://i.imgur.com/wdNYLOQ.png

It is assigning fallback status to orders after deleting the plugin.

So, I am closing this issue.
