### ISSUE TITLE
Add an option to Bulk Delete the Custom Order Status

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/custom-order-statuses-woocommerce#23]
When there are multiple custom statues to be deleted, it will be time-consuming to delete them one by one: https://prnt.sc/rnqjxe

So, an option to multi-select the custom status and bulk delete them will be good.

**Comment by nitin-ts** [comment]
Hello,
in version 2.0.0, we have used a custom post type for the statuses so now bulk deleting of statuses is possible
https://i.imgur.com/XsOPaoj.png

So, I am closing this issue.
