### ISSUE TITLE
After deleting the plugin old data does not get removed.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/custom-order-statuses-woocommerce#42]
**Describe the bug**
After deleting the plugin old data does not get removed.

**To Reproduce**
1. On my local I have a COS lite plugin
2. Deactivate plugin
3. Delete the plugin
4. again reinstall the plugin (Add new--upload), but Old COS Status does not remove
https://www.screencast.com/t/YpnwYmjzlXze

**Expected behavior**
Old data should be removed after deleting the plugin.

**Comment by apeksha10** [comment]
The above issue is the same as we have in Pro #34
Below are the steps 
1. Upload a latest live copy
2. Create Custom status
3. placed some order for newly created custom status
4. delete the plugin, I noticed Orders are getting deleted which has the custom order status.

**Comment by nitin-ts** [comment]
Hello,

this issue has been fixed by PR #51 for issue #21 
I have tested it in my localhost and it is working fine.
