### ISSUE TITLE
The custom order status bulk action is not working.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/custom-order-statuses-woocommerce#64]
**Describe the bug**
The custom order status bulk action is not working.

The client's statement is: 

None of the custom order statuses are showing in the bulk action dropdown on the orders page.
I have changed status to completed and few other random ones but nothing else.

**To Reproduce**
I was unable to reproduce it at our end.

**Expected behavior**
The bulk action should show all the custom statuses. 

**Additional context**
Link: https://wordpress.org/support/topic/order-bulk-actions-not-showing/

Here is the solution:

It’s the bug alg_get_custom_order_statuses_from_cpt function. Check the folder in /includes/class-alg-wc-custom-order-statuses-core.php . This function is not solid to hanlde the bulk action.Turn back to use alg_get_custom_order_statuses would be alright. Hope the author could resolve this issue rapidly.

/includes/class-alg-wc-custom-order-statuses-core.php
.
.
.
public function register_order_custom_status_bulk_actions( $bulk_actions ) {
			// $custom_order_statuses = alg_get_custom_order_statuses_from_cpt( true ); // <-- there is the bug happend.
			$custom_order_statuses = alg_get_custom_order_statuses( true ); // Turn back to deprecated(maybe) function.
			foreach ( $custom_order_statuses as $slug => $label ) {
				// translators: New Status.
				$bulk_actions[ 'mark_' . $slug ] = sprintf( __( 'Change status to %s', 'custom-order-statuses-woocommerce' ), $label );
			}
			return $bulk_actions;
		}

**Comment by PratapDungrani** [comment]
@kartikparmar No action required. The current implementation is better than the suggested one.
