### ISSUE TITLE
When slug in custom order status starts with wc- then Order status don't gets changed to that custom order status.

### ISSUE THREAD

**Issue by Shasvat7** [TycheSoftwares/custom-order-statuses-woocommerce#67]
**Describe the bug**
When the custom order status is created with the slug value starting with WC-, the order status doesn't change to that custom order status.

**To Reproduce**
1. Create a COS with slug value starting with wc-
2. Set that COS, as a default status for the BACS/COD payment method
3. Then place the order with BACS?COD payment method
4. Visit the orders page, where you will see that status of that order has not changed to the COS

**Expected behavior**
Order status should get changed to the custom order status.

**Additional context**
This issue was reported in the Pro plugin, but it is present in the lite version too, hence added the issue.

For this issue, we will not save the slug of the COS starting with wc-, if anyone enters it and tries to update the COS then wc- part will be removed from the slug because in the bulk action on the orders page WooCommerce will not change the order status to the COS having slug starting with wc-, hence we need to remove them.

**Comment by apeksha10** [comment]
With the latest git copy, I am able to replicate the above issue.

steps
1. Create new custom order status. https://www.screencast.com/t/u0VsLyqzj14
2. Assing COS to Cash on delivery default status. https://www.screencast.com/t/pWpO09vm
3. Place an order using COD. https://www.screencast.com/t/F5IqWoL9p
4. Go to the woo-order page, COS is not getting updated. https://www.screencast.com/t/7WcnVjK9zz


Hence I have re-open this issue.
