### ISSUE TITLE
The content of the shortcodes available in email should have been translated. 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/custom-order-statuses-woocommerce#79]
**Describe the bug**
The content of the shortcodes available in email should have been translated. 

Allow to translate {order_details} in the costum email.

I can't find the following strings under any plugin:
Billing address, Quantity, Price, Subtotal, Shipping, VAT, Payment Method, Total, Shipping address

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/37301

**Comment by PratapDungrani** [comment]
@kartikparmar Chetna has already replied with the correct answer. We are using the WooCommerce template for order details and hence no need for conversion from our side. It must be managed from the WooCommerce side. If the client is unable to get translated version, we could suggest better translation plugin.

Let me know.

Thanks
