### ISSUE TITLE
Add tracking data in plugin: Settings, admin choice and data tracking

### ISSUE THREAD

**Issue by nidhitatosaniya** [TycheSoftwares/custom-order-statuses-woocommerce#86]
**Describe the bug**
Add the data tracking code in the plugin to ensure all the relevant details (global settings, product settings etc.) are sent back to the tracking server.

**Additional context**
https://docs.google.com/document/d/1T-4QcwvO1K-dZLFQwOxC_xvPjX4QFFXuSqt1bNn7lU4/edit

**Comment by pinalj** [comment]
The tracking code needs to be implemented at v2

Tyche Javascript Constructor: https://github.com/TycheSoftwares/tyche-js-constructor
Plugin Tracking: https://github.com/TycheSoftwares/tyche-plugin-tracking
Plugin Deactivation: https://github.com/TycheSoftwares/tyche-plugin-deactivation
