### ISSUE TITLE
Incompatible with ‘High-Performance order storage (COT)

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/custom-order-statuses-woocommerce#96]
**Describe the bug**
I found incompatibility with HPOS for this plugin. I received the following notice from WP/Woocommerce when trying to update the tables in a staging environment:

![image](https://user-images.githubusercontent.com/15136179/232817152-59da7cf6-2344-467d-85e1-c006c7b62ae6.png)

**Additional context**

**Comment by nidhitatosaniya** [comment]
We should deactivate lite version if pro version is activated. 
Included PR : https://github.com/TycheSoftwares/custom-order-statuses-for-woocommerce-pro/pull/233
